VWDemo/force-app/main/default/objects/OpportunityLineItem/fields/Has_subscription__c.field-meta.xml
<CustomField>
    <fullName>Has_subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if Product is sold with a subscription</description>
    <inlineHelpText>Yearly subscription is sold alongside product</inlineHelpText>
    <label>Has subscription?</label>
    <type>Checkbox</type>
</CustomField>

VWDemo/force-app/main/default/objects/OpportunityLineItem/fields/Subscription_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Percentage__c</fullName>
    <description>Percentage to be added to product price</description>
    <inlineHelpText>Percentage to be added to product price.</inlineHelpText>
    <label>Subscription Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>10</label>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

VWDemo/force-app/main/default/classes/OpportunityLineItemTriggerHandler.cls
public without sharing class OpportunityLineItemTriggerHandler {
    
    public static void adjustLineItem(List<OpportunityLineItem> oppLineItemList) {
        
        // for each line item adjust unit price based on subscription percentage
        for(OpportunityLineItem auxOppLine : oppLineItemList) {
            
            // calculate percentage and set Unit Price
            if(auxOppLine.Has_subscription__c && auxOppLine.Subscription_Percentage__c != null){
                Decimal subscriptionPercentage = (Decimal.valueOf(auxOppLine.Subscription_Percentage__c)/100);               
                auxOppLine.UnitPrice = auxOppLine.UnitPrice + (auxOppLine.UnitPrice * subscriptionPercentage);  
            }
            // set Subscription_Percentage__c to 0
            else if(!auxOppLine.Has_subscription__c) {
                auxOppLine.Subscription_Percentage__c = '0';
            }
        }
    }
    
    public static void adjustLineItemOnUpdate(List<OpportunityLineItem> oppLineItemList, Map<Id, OpportunityLineItem> oldMap) {
        
        // for each line item adjust unit price based on subscription percentage
        for(OpportunityLineItem auxOppLine : oppLineItemList) {
            
            // calculate percentage and set Unit Price
            if(auxOppLine.Has_subscription__c && auxOppLine.Subscription_Percentage__c != null){ 
                Decimal subscriptionPercentage = (Decimal.valueOf(auxOppLine.Subscription_Percentage__c)/100);               
                auxOppLine.UnitPrice = auxOppLine.ListPrice + (auxOppLine.ListPrice * subscriptionPercentage);  
            }
            
            // set Subscription_Percentage__c to 0
            else if(!auxOppLine.Has_subscription__c) {
                auxOppLine.Subscription_Percentage__c = '0';
            }
        }
    }
}